mqtt:
  sensor:
    - name: "Room Temperature"
      state_topic: "dht11/temp"
      unit_of_measurement: "°C"
      device_class: temperature
      value_template: "{{ value | float }}"
      unique_id: roomsense_temperature

    - name: "Room Humidity"
      state_topic: "dht11/humidity"
      unit_of_measurement: "%"
      device_class: humidity
      value_template: "{{ value | float }}"
      unique_id: roomsense_humidity

    - name: "Room CO2"
      state_topic: "ndir/co2"
      unit_of_measurement: "ppm"
      device_class: carbon_dioxide
      value_template: "{{ value | int }}"
      unique_id: roomsense_co2


automation: !include automations.yaml
