- id: roomsense_co2_high_alert
  alias: "RoomSense CO2 visoka razina"
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.room_co2
      above: 1000
  action:
    - service: persistent_notification.create
      data:
        title: "Upozorenje - CO2"
        message: "CO2 razina je {{ states('sensor.room_co2') }} ppm. Potrebno je provjetravanje."
        notification_id: roomsense_co2_alert

- id: roomsense_co2_critical_alert
  alias: "RoomSense CO2 kriticna razina"
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.room_co2
      above: 2000
  action:
    - service: persistent_notification.create
      data:
        title: "Kriticno - CO2"
        message: "CO2 razina je {{ states('sensor.room_co2') }} ppm. Potrebno je hitno provjetravanje."
        notification_id: roomsense_co2_critical

- id: roomsense_co2_normal
  alias: "RoomSense CO2 normalizacija"
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.room_co2
      below: 800
  action:
    - service: persistent_notification.dismiss
      data:
        notification_id: roomsense_co2_alert
    - service: persistent_notification.dismiss
      data:
        notification_id: roomsense_co2_critical

- id: roomsense_temperature_high_alert
  alias: "RoomSense temperatura previsoka"
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.room_temperature
      above: 35
  action:
    - service: persistent_notification.create
      data:
        title: "Upozorenje - temperatura"
        message: "Temperatura je {{ states('sensor.room_temperature') }} °C."
        notification_id: roomsense_temperature_alert

- id: roomsense_temperature_low_alert
  alias: "RoomSense temperatura preniska"
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.room_temperature
      below: 15
  action:
    - service: persistent_notification.create
      data:
        title: "Upozorenje - temperatura"
        message: "Temperatura je {{ states('sensor.room_temperature') }} °C."
        notification_id: roomsense_temperature_alert

- id: roomsense_temperature_normal
  alias: "RoomSense temperatura normalizacija"
  mode: single
  trigger:
    - platform: numeric_state
      entity_id: sensor.room_temperature
      above: 15
      below: 35
  action:
    - service: persistent_notification.dismiss
      data:
        notification_id: roomsense_temperature_alert
